version: '3.8'

services:
  web:
    build: .
    container_name: logistics-app
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - ./shipments.json:/app/shipments.json
    environment:
      - FLASK_ENV=production
    networks:
      - logistics-network

  nginx:
    image: nginx:alpine
    container_name: logistics-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - logistics-network

networks:
  logistics-network:
    driver: bridge
